version: '3'

services:
  db:
    image: 'postgres:12.9'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=cactus123
    ports:
      - '5432:5432'